name: 'dbt_bigquery_project'
version: '1.0'
config-version: 2

vars:
  category: Seafood

profile: 'northwind'

model-paths: ["models"]

models:
  dbt_bigquery_project:
    +pre-hook:
      - "{{ log_event('START') }}"
    +post-hook:
      - "{{ log_event('END') }}"      